# Generated by Django 6.0.1 on 2026-02-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid'), ('overpaid', 'Overpaid')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid'), ('overpaid', 'Overpaid')], default='unpaid', max_length=20),
        ),
    ]
