# Generated by Django 6.0.1 on 2026-02-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_purchases', '0002_alter_purchase_status_alter_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid')], max_length=20, null=True),
        ),
    ]
