# Generated by Django 6.0.1 on 2026-02-10 02:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_feature_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
