# Generated by Django 6.0.1 on 2026-02-11 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscription_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Bank ref or Telebirr ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
