# Generated by Django 6.0.1 on 2026-02-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_feature_is_active_alter_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('trialing', 'Trialing')], default='active', max_length=20),
            preserve_default=False,
        ),
    ]
