# Generated by Django 6.0.1 on 2026-02-11 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('subscriptions', '0006_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active (Paid)'), ('pending_payment', 'Pending Payment'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
