# Generated by Django 6.0.1 on 2026-02-19 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('sales_purchases', '0004_alter_purchase_status_alter_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='linked_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='sales_purchases.purchase'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='linked_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='sales_purchases.sale'),
        ),
    ]
