# Generated by Django 6.0.1 on 2026-05-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_category_transaction_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('revenue', 'Revenue (Sale)'), ('refund_in', 'Refund from Supplier'), ('cogs', 'Cost of Goods (Purchase)'), ('expense', 'Business Expense'), ('refund_out', 'Refund to Customer'), ('capital', 'Capital / Owner Deposit')], max_length=20),
        ),
    ]
