# Generated by Django 6.0.1 on 2026-02-20 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_category_company'),
        ('sales_purchases', '0004_alter_purchase_status_alter_sale_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='type',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('adjustment', 'Adjustment')], default='adjustment', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_purchases.purchase'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_purchases.sale'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
