# Generated by Django 6.0.1 on 2026-02-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_category_options_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit_measure',
            field=models.CharField(choices=[('piece', 'Piece'), ('kg', 'Kilogram'), ('liter', 'Liter'), ('box', 'Box')], default='piece', max_length=20),
        ),
    ]
