# Generated by Django 6.0.1 on 2026-02-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_item_unit_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit_measure',
            field=models.CharField(default='piece', max_length=20),
        ),
    ]
