# Generated by Django 6.0.1 on 2026-01-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('business_admin', 'Business Admin'), ('employee', 'Employee'), ('super_admin', 'Super Admin')], default='business_admin', max_length=20),
        ),
    ]
